### PR TITLE
Add [dq, dp, qi] attributes to jwk for compatibility with other libs

### PR DESCRIPTION
**Pull request by InformatiQ**
Add [dq, dp, qi] attributes to jwk for compatibility with other libs that require them such as the .NET jwk libs

### CODE REVIEW

**Comment by nov** [comment]
thanks

**Comment by nov** [comment]
BTW, which .NET jwk library do you use?

**Comment by ziaulrehman40** [comment]
I am not getting these extra params when i do:
```
key = OpenSSL::PKey::RSA.generate(2048)
key.public_key.to_jwk(kid: Time.now.utc.iso8601).to_json
```

Am i missing something?

**Comment by nov** [comment]
Because it's not a private key.

**Comment by ziaulrehman40** [comment]
Yeah i am sorry, i got confused by these instructions:
https://github.com/instructure/canvas-lms/blob/master/config/dynamic_settings.yml.example#L91

The key already there has all these extra values but the one I was generating with their instructions was missing these values. IDK if i should put `key.public_key.to_jwk`'s value in there or `key.to_jwk`'s value.

Anyway, thank you for your prompt response.

**Pull request merged**
