### PR TITLE
Remove url_safe_base64 gem

### PR DESCRIPTION
**Pull request by bdewater**
Since Ruby 2.3 (https://github.com/ruby/ruby/commit/6b6680945ed3274cddbc34fdfd410d74081a3e94), `Base64.urlsafe_encode64` supports the `padding` argument which makes url_safe_base64 redundant.

Besides removing a dependency, there's also a nice speedup especially when encoding.

<details>
<summary>Benchmark script</summary>

```ruby
require 'base64'
require 'url_safe_base64'
require 'benchmark/ips'

HEADER = "{\"alg\":\"HS256\",\"typ\":\"JWT\"}"
ENCODED_SIGNATURE = 'DyuTgO2Ggb5nrhkkhI-RjVYIBe3o8oL4ijkAn94YPxQ'

def ruby_stdlib_decode
  Base64.urlsafe_decode64 ENCODED_SIGNATURE
end

def ruby_stdlib_encode
  Base64.urlsafe_encode64 HEADER, padding: true
end

def url_safe_base64_decode
  UrlSafeBase64.decode64 ENCODED_SIGNATURE
end

def url_safe_base64_encode
  UrlSafeBase64.encode64 HEADER
end

Benchmark.ips do |x|
  # x.report("ruby_stdlib_decode") { ruby_stdlib_decode }
  x.report("ruby_stdlib_encode") { ruby_stdlib_encode }
  # x.report("url_safe_base64_decode") { url_safe_base64_decode }
  x.report("url_safe_base64_encode") { url_safe_base64_encode }
  x.compare!
end
```
</details>

```
ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

Calculating -------------------------------------
  ruby_stdlib_decode    667.957k (± 2.7%) i/s -      3.380M in   5.064439s
url_safe_base64_decode
                        625.138k (± 1.9%) i/s -      3.134M in   5.015475s

Comparison:
  ruby_stdlib_decode:   667956.5 i/s
url_safe_base64_decode:   625138.4 i/s - 1.07x  slower
```
```
Calculating -------------------------------------
  ruby_stdlib_encode    827.585k (± 1.5%) i/s -      4.205M in   5.081808s
url_safe_base64_encode
                        208.017k (± 2.1%) i/s -      1.040M in   5.000153s

Comparison:
  ruby_stdlib_encode:   827584.8 i/s
url_safe_base64_encode:   208017.4 i/s - 3.98x  slower
```

### CODE REVIEW

**Comment by nov** [comment]
thanks for your contribution!

**Comment by urkle** [comment]
@nov so why was a change like this included in point release of the json-jwt gem?  This caused us a bit of issues when this gem was upgraded by a developer (due to upgrading our auth gem which pulls openid_connect)..   And since some of our apps are still on Ruby 2.2.x it caused things to break severely. 

We are in the process if upgrading to 2.4.  But this kind of change shouldn't have happened in a point release of a gem like this.

**Comment by bdewater** [comment]
I proposed this patch because I noticed 2.2 was not tested on Travis anymore. Turns out this change was made for 1.9.0 but the gemspec did not indicate this requirement.

Compatibility could be restored by using a refinement with the base64 code from Ruby 2.3.

**Comment by urkle** [comment]
@bdewater right now we are using version 1.9.2 of this gem on Ruby 2.2.5/2.2.6 and it works fine.  IT was only after updating to 1.9.4 that things blew up. (as this actual PR was included in the 1.9.3 release)

I would highly recommend that some better checking of minimum requirements is set into release policy so that this kind of issue does not happen in the future.. As It took my developer and I a few hours to track down what had happened and where it broke.

**Pull request merged**
