### PR TITLE
Add JSON::JWT.decode_with_keys

### PR DESCRIPTION
**Pull request by wader**
Decode token given a array of keys [{:kid => ..., :key => ...}, ...].
Makes it possible to match kid in JOSE header to use correct key when there are
multiple public keys.

### CODE REVIEW

**Comment by wader** [comment]
Required by nov/openid_connect#23

**Comment by nov** [comment]
Probably refactoring `JSON::JWK` & `JSON::JWK::Set` is the best way for easy to read coding.
Let me try it first.

Thanks for your contribution!

**Comment by nov** [comment]
This commit will allow you to give `JSON::JWK::Set` instance as public key on `JSON::JWT.decode`.
Isn't it wat you really expect?
https://github.com/nov/json-jwt/commit/a4f1fc5e3f06070690a6643e32e6146861ac5efa

**Comment by wader** [comment]
Looks more sane than my attempt :+1: so no changes is need to openid_connect? but omniauth-openid-connect still need a change to use multiple keys right? i.e. https://github.com/jjbohn/omniauth-openid-connect/blob/master/lib/omniauth/strategies/openid_connect.rb#L128 `public_key` method needs to change `config.public_keys.first` to just `config.jwks`?

**Comment by nov** [comment]
You're totally right.

**Comment by wader** [comment]
Ok! ill test it later today or tomorrow and let you know. Big thanks!

**Comment by wader** [comment]
Seems to work fine. Could you make a new release?

omniauth-openid-connect does not seems to depend on json-jwt directly, only on openid_connect. So what do you think would be best:

Add an explicit depend on new version of json-jwt for omniauth-openid-connect
Or
Update json-jwt version for openid_connect and then update openid_connect version for omniauth-openid-connect?

**Comment by nov** [comment]
OK, I've just released json-jwt v1.2.1 with the above commit.
I've also released openid_connect v0.9.0 with gem dependency updates (not only json-jwt but also other my gems used in openid_connect gem https://github.com/nov/openid_connect/commit/14d9d5dff7e9dce43600597d1e5b24ad321e8364)

So omniauth_openid_connect doesn't need to specify json-jwt version, just update minimum openid_connect version to v0.9.0.

**Comment by wader** [comment]
Very nice. Thanks for all the help!

**Pull request closed without merging**
